### ISSUE TITLE
Version detect fails

### ISSUE THREAD

**Issue by andrew-barnett** [microsoft/codeql-container#15]
```sh
Could not determine existing codeql version
Traceback (most recent call last):
  File "/usr/local/startup_scripts/setup.py", line 57, in <module>
    setup()
  File "/usr/local/startup_scripts/setup.py", line 39, in setup
    get_latest_codeql(args)
  File "/usr/local/startup_scripts/setup.py", line 44, in get_latest_codeql
    current_installed_version = codeql.get_current_local_version()
  File "/usr/local/startup_scripts/libs/codeql.py", line 74, in get_current_local_version
    exit(ERROR_EXECUTING_CODEQL)
NameError: name 'ERROR_EXECUTING_CODEQL' is not defined
Error 1 executing from command.
Exiting...
Command Output: 
[2020-12-01 12:15:08,245] INFO: Starting setup...
```

The 2.3.2 and 2.4.0 tags of the base codeql util reports version differently than expected:
```sh
$ docker run -it --entrypoint /bin/bash mcr.microsoft.com/cstsectools/codeql-container:latest
root@64e686e098fd:/# /usr/local/codeql-home/codeql/codeql version
CodeQL command-line toolchain release 2.3.2.
Copyright (C) 2019-2020 GitHub, Inc.
Unpacked in: /usr/local/codeql-home/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.
```

```sh
root@6f4812e540a7:/# /usr/local/codeql-home/codeql/codeql version
CodeQL command-line toolchain release 2.4.0.
Copyright (C) 2019-2020 GitHub, Inc.
Unpacked in: /usr/local/codeql-home/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.
```

**Comment by rajasoun** [comment]
Patch Fix: Till the merge happens
----
Dockerfile.patch

FROM mcr.microsoft.com/cstsectools/codeql-container
RUN sed -i 's/Version:/release/g'  /usr/local/startup_scripts/libs/codeql.py

ENV PYTHONIOENCODING=utf-8
ENTRYPOINT ["python3", "/usr/local/startup_scripts/startup.py"] 

-------
docker build . -f Dockerfile.patch -t codeql-container

**Comment by Manouchehri** [comment]
I don't think this patch is needed anymore?

**Comment by femigr** [comment]
> ## Patch Fix: Till the merge happens
> 
> Dockerfile.patch
> 
> FROM mcr.microsoft.com/cstsectools/codeql-container
> RUN sed -i 's/Version:/release/g' /usr/local/startup_scripts/libs/codeql.py
> 
> ENV PYTHONIOENCODING=utf-8
> ENTRYPOINT ["python3", "/usr/local/startup_scripts/startup.py"]
> 
> docker build . -f Dockerfile.patch -t codeql-container

Having the same issue... the patch gets me a bit further but I am getting another error now which also seems to result from some environment variable problems: 
```
sudo docker run codeql-container -e CODEQL_CLI_ARGS="analyze"
[2021-07-05 15:03:50,045] INFO: No argument passed in for codeql-cli, nothing to do. To perform some task, please set the CODEQL_CLI_ARGS environment variable to a valid argument...
```
I guess I'll just avoid using this image for now

**Comment by jacobmsft** [comment]
The new image is updated and code is fixed. I'll close this issue, open a new issue if problem persists.
