### ISSUE TITLE
NameError: name 'ERROR_EXECUTING_CODEQL' is not defined

### ISSUE THREAD

**Issue by sbilello** [microsoft/codeql-container#19]
```
❯ docker run --rm --name codeql-container -e CODEQL_CLI_ARGS="resolve qlpacks"  mcr.microsoft.com/cstsectools/codeql-container

Could not determine existing codeql version
Traceback (most recent call last):
  File "/usr/local/startup_scripts/setup.py", line 57, in <module>
    setup()
  File "/usr/local/startup_scripts/setup.py", line 39, in setup
    get_latest_codeql(args)
  File "/usr/local/startup_scripts/setup.py", line 44, in get_latest_codeql
    current_installed_version = codeql.get_current_local_version()
  File "/usr/local/startup_scripts/libs/codeql.py", line 74, in get_current_local_version
    exit(ERROR_EXECUTING_CODEQL)
NameError: name 'ERROR_EXECUTING_CODEQL' is not defined
Command Output:
[2021-03-08 23:32:49,409] INFO: Starting setup...

Error 1 executing from command.
Exiting...
```

**Comment by outime** [comment]
Is this maintained at all? @jacobmsft @scovetta

**Comment by jacobmsft** [comment]
Hey outime, yes we push updates to the container registry but code has not been modified for a while...I'll look at the issue.

**Comment by cozyviking** [comment]
I was experiencing the same issue and noticed that the CLI output for the version string of codeql no longer matches a search for "Version:." I have a proposed change for fixing this here: https://github.com/microsoft/codeql-container/pull/30

**Comment by cozyviking** [comment]
@sbilello now that PR [#31](https://github.com/microsoft/codeql-container/pull/31) has been merged, you should re-test and see if this resolves your issue. Testing locally, it does appear to resolve my issue which was very similar.
