### ISSUE TITLE
`CODEQL_GITHUB_URL` is never used

### ISSUE THREAD

**Issue by RA80533** [microsoft/codeql-container#27]
https://github.com/microsoft/codeql-container/blob/d0e531a4b7db837e7e92e8d611b1226eb45ef861/container/libs/codeql.py#L37

It seems that the constant was meant to be used in place of the hardcoded URLs for downloading the CLI binaries. Simply replacing the base of hardcoded URL with the constant would leave the remaining portion of the URL hardcoded.

**Comment by RA80533** [comment]
Duplicate of #19

**Comment by jacobmsft** [comment]
Thanks RA80533, this should be fixed. I'll close this issue, open a new issue if problem persists.

**Comment by RA80533** [comment]
Resolved in https://github.com/microsoft/codeql-container/commit/7de62934385e6598cbe4e837bf8d79c3242d34e4
