### ISSUE TITLE
Docker build fails: Could not resolve library path for /usr/local/codeql-home/codeql-repo/ruby/ql/src

### ISSUE THREAD

**Issue by vlkl-sap** [microsoft/codeql-container#35]
% git describe --always
beb1e2c

% docker build . -f Dockerfile -t codeql-container
[...]
[compiling queries]
[...]
Done [886/911 comp 3.4s] /usr/local/codeql-home/codeql-repo/python/ql/src/Metrics/FLinesOfComments.ql.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/usr/local/codeql-home/codeql-repo/ruby/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /usr/local/codeql-home/codeql-repo/ruby/ql/src
The command '/bin/sh -c codeql query compile --threads=0 ${CODEQL_HOME}/codeql-repo/*/ql/src/codeql-suites/*.qls' returned a non-zero code: 2

Also: the image on docker hub is 1 year old. Would it be possible to publish a newer one?

Thanks!

**Comment by InbarRose** [comment]
I have a the same error,
but the error is a bit different...

```
Done [889/914 comp 4s] /usr/local/codeql-home/codeql-repo/python/ql/src/Metrics/FNumberOfTests.ql.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/usr/local/codeql-home/codeql-repo/ruby/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /usr/local/codeql-home/codeql-repo/ruby/ql/src
The command '/bin/sh -c codeql query compile --threads=0 ${CODEQL_HOME}/codeql-repo/*/ql/src/codeql-suites/*.qls' returned a non-zero code: 2
```

**Comment by jacobmsft** [comment]
This seems to be an issue with the github codeql packages. I have filed an issue with codeql:  https://github.com/github/codeql/issues/7193

**Comment by jacobmsft** [comment]
This is fixed in the latest checkin and image. I'll close this issue, open a new issue if problem persists.
