### ISSUE TITLE
container tags by version

### ISSUE THREAD

**Issue by InbarRose** [microsoft/codeql-container#36]
it would be great to have container tags by version, and not only "latest" as this could break existing flows if the "latest" tag is updated.

using this manifest: https://mcr.microsoft.com/v2/cstsectools/codeql-container/tags/list
I can see that only "latest" exists.

**Comment by jacobmsft** [comment]
I'm adding this with automated builds. The container image should also show the checkin hash going forward.

**Comment by jacobmsft** [comment]
This is added. The latest image has a date tag and a checkin hash along with the latest tag. I'll close this issue, open a new issue if problem persists.
